# File Configuration > initial parms
files:
  max_depth: 5
  allowed_extensions:
    - jpg
    - png
    - gif
    - txt
    - sh
    - py
    - .obj
  ignore_patterns:
    - "*hidden.*"
    - "_"
    - "."
    - ".git"
    - ".gitignore"
  text_files_to_images: true
  folder_names_to_images: true

# Display Settings > initial parms
display:
  sort:
    - date
    - size
    - user
  mobile:
    switch_to_mobile_when: "50%"
    show_dir_tree: true
    show_html_content: true
    show_theejs_scene: true

# Path Configuration  > initial parms
paths:
  config: "./config.yml"
  src: "src"
  logs: "logs"

# Media Settings  > initial parms
media:
  image_quality: 85
  html_content:
    dimensions:
      desktop: [800, 600]
      mobile: [800, 600]
    paths:
      desktop_path: "processed"
      mobile_path: "processed"
  threejs_scene:
    dimensions:
      desktop: [800, 600]
      mobile: [800, 600]
    paths:
      desktop_path: "processed"
      mobile_path: "processed"

# Directory Tree Configuration  > initial parms
dir_tree: {}

# HTML Content Configuration > initial parms
html_content: {}

# Three.js Scene Configuration > initial parms
threejs_scene:
  appearance:
    transparency_color: "black"
  render:
    show_foldernames_as_images: true
    show_textfils_as_images: true
    show_comment_tags: true
    show_stack_tags: true
  performance:
    max_instances: 1000
    grid_size: 10
    spacing: 0

#-----------------------------------------------------
# Application Information  > generated by py afterwards
info:
  version: "0.0.1"
  build_id: 23  
  timestamp: "2024_12_34"

# git Information  > generated by py afterwards
git:
  git_branch: "dev"

# Statistics  > generated by py afterwards
stats:
  total_projects: 12
  total_files: 333
  total_folders: 79
  total_size: 3333
  last_modified: "19_29_34"

# Directory Tree > generated by py afterwards
tree:
  - "root/"
  - "├── README.md                 (1.0 KB)"
  - "├── src/"
  - "│   └── api/"
  - "│       └── add-comment.js    (2.0 KB)"
  - "└── upload.sh               (512 B)"



