# config/base.yaml
version: "1.0.0"
build:
  env: development
  cache_dir: ".cache"
  max_depth: 5
  
paths:
  content: "content"
  output: "dist"
  logs: "logs"
  temp: ".temp"
  cache: ".cache"

images:
  formats:
    - jpg
    - png
    - gif
    - webp
  sizes:
    thumbnail: [150, 150]
    preview: [800, 600]
    full: [1920, 1080]
  optimization:
    jpg_quality: 85
    png_compression: 9
    webp_quality: 80
  max_file_size: 2000000  # 2MB

three_js:
  grid_size: 10
  spacing: 2
  texture_size: 1024
  max_instances: 1000
  lod_levels: [500, 1000, 2000]

performance:
  max_texture_memory: 1000000000  # 1GB
  target_fps: 60
  batch_size: 100

logging:
  level: INFO
  rotation: "1 week"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  files:
    build: "logs/build.log"
    error: "logs/error.log"
    performance: "logs/performance.log"

github:
  lfs_patterns:
    - "*.jpg"
    - "*.png"
    - "*.gif"
    - "*.webp"
  branches:
    production: main
    development: develop
